[91mERROR:[92m[07/10/2024 01:52:05 PM][0m: 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
(leitura_csv_insercao_bd_sql) finalizada com erro abaixo: 
 (smallint out of range
)
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "/Users/bruno/GitHub/Projeto_ETL_RFB_IBGE_ANP-master/src/B_Def_Global.py", line 1079, in leitura_csv_insercao_bd_sql
    execute_batch(cur, insert_query, data_tuples)
  File "/Users/bruno/GitHub/Projeto_ETL_RFB_IBGE_ANP-master/__my_env/lib/python3.11/site-packages/psycopg2/extras.py", line 1216, in execute_batch
    cur.execute(b";".join(sqls))
psycopg2.errors.NumericValueOutOfRange: smallint out of range

[91mERROR:[92m[07/10/2024 01:53:33 PM][0m: 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
(leitura_csv_insercao_bd_sql) finalizada com erro abaixo: 
 (column "data_situacao_cadastral" is of type date but expression is of type integer
LINE 3: ..., 2, 'LOJAS PONTES MOVEIS E ELETRODOMESTICOS', 4, 20180925, ...
                                                             ^
HINT:  You will need to rewrite or cast the expression.
)
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "/Users/bruno/GitHub/Projeto_ETL_RFB_IBGE_ANP-master/src/B_Def_Global.py", line 1079, in leitura_csv_insercao_bd_sql
    execute_batch(cur, insert_query, data_tuples)
  File "/Users/bruno/GitHub/Projeto_ETL_RFB_IBGE_ANP-master/__my_env/lib/python3.11/site-packages/psycopg2/extras.py", line 1216, in execute_batch
    cur.execute(b";".join(sqls))
psycopg2.errors.DatatypeMismatch: column "data_situacao_cadastral" is of type date but expression is of type integer
LINE 3: ..., 2, 'LOJAS PONTES MOVEIS E ELETRODOMESTICOS', 4, 20180925, ...
                                                             ^
HINT:  You will need to rewrite or cast the expression.

[91mERROR:[92m[07/10/2024 01:53:55 PM][0m: 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
(leitura_csv_insercao_bd_sql) finalizada com erro abaixo: 
 (column "data_entrada_sociedade" is of type date but expression is of type integer
LINE 3: ...12, 2, 'FABRICIO NATALE PERO', '***474797**', 49, 20060912, ...
                                                             ^
HINT:  You will need to rewrite or cast the expression.
)
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "/Users/bruno/GitHub/Projeto_ETL_RFB_IBGE_ANP-master/src/B_Def_Global.py", line 1079, in leitura_csv_insercao_bd_sql
    execute_batch(cur, insert_query, data_tuples)
  File "/Users/bruno/GitHub/Projeto_ETL_RFB_IBGE_ANP-master/__my_env/lib/python3.11/site-packages/psycopg2/extras.py", line 1216, in execute_batch
    cur.execute(b";".join(sqls))
psycopg2.errors.DatatypeMismatch: column "data_entrada_sociedade" is of type date but expression is of type integer
LINE 3: ...12, 2, 'FABRICIO NATALE PERO', '***474797**', 49, 20060912, ...
                                                             ^
HINT:  You will need to rewrite or cast the expression.

[96mINFO:[92m[07/10/2024 02:00:23 PM][0m: ... (verificar_repetidos_tabelas) executada para verifica√ß√£o de cnpj repetidos na coluna id_cod_cnpj_basico no arquivo/tabela (tb_rfb_empresas) 
Com tempo de (00:00:01)h:mim:s ...
[96mERROR:[92m[07/10/2024 02:00:23 PM][0m: 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
(remover_repetidos_tabelas) finalizada com erro abaixo: 
 (cannot unpack non-iterable NoneType object)
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "/Users/bruno/GitHub/Projeto_ETL_RFB_IBGE_ANP-master/src/B_Def_Global.py", line 1501, in remover_repetidos_tabelas
    df_list, df_ori, valor_tmp = verificar_repetidos_tabelas(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
[96mINFO:[92m[07/10/2024 02:00:25 PM][0m: ... (verificar_repetidos_tabelas) executada para verifica√ß√£o de cnpj repetidos na coluna id_cod_cnpj_completo_num no arquivo/tabela (tb_rfb_estabelecimentos) 
Com tempo de (00:00:01)h:mim:s ...
[96mERROR:[92m[07/10/2024 02:00:25 PM][0m: 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
(remover_repetidos_tabelas) finalizada com erro abaixo: 
 (cannot unpack non-iterable NoneType object)
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "/Users/bruno/GitHub/Projeto_ETL_RFB_IBGE_ANP-master/src/B_Def_Global.py", line 1501, in remover_repetidos_tabelas
    df_list, df_ori, valor_tmp = verificar_repetidos_tabelas(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
[96mINFO:[92m[07/10/2024 02:00:25 PM][0m: ### O processo total (cnpj_repetidos_rfb) de verifica√ß√£o/remo√ß√£o de cnpj repetidos nas tabelas na dados_rfb foi finalizado... 
 Com tempo de (00:00:04)h:mim:s ###
